{
  imports = [
    ./generic/all-modules.nix

    ./lib/package.nix

    ./misc/catppuccin.nix
    ./misc/deuxfleurs.nix
    ./misc/editorconfig.nix
    ./misc/files.nix
    ./misc/home.nix
    ./misc/music.nix
    ./misc/nix.nix
    ./misc/opengl.nix
    ./misc/packages.nix
    ./misc/secrets.nix
    ./misc/systemd.nix

    ./programs/bat.nix
    ./programs/bpython.nix
    ./programs/discord.nix
    ./programs/element.nix
    ./programs/fd.nix
    ./programs/ferdium.nix
    ./programs/fish.nix
    ./programs/gh.nix
    ./programs/git.nix
    ./programs/glab.nix
    ./programs/gpg.nix
    ./programs/hyfetch.nix
    ./programs/imhex.nix
    ./programs/kde.nix
    ./programs/kitty.nix
    ./programs/litecli.nix
    ./programs/llvm.nix
    ./programs/mise.nix
    ./programs/mux.nix
    ./programs/neovim.nix
    ./programs/nix-init.nix
    ./programs/nvchecker.nix
    ./programs/obsidian.nix
    ./programs/paru.nix
    ./programs/password-store.nix
    ./programs/pgcli.nix
    ./programs/powerline.nix
    ./programs/rust.nix
    ./programs/sccache.nix
    ./programs/silicon.nix
    ./programs/ssh.nix
    ./programs/starship.nix
    ./programs/taplo.nix
    ./programs/tmux.nix
    ./programs/xh.nix
    ./programs/yazi.nix
    ./programs/yt-dlp.nix

    ./services/aria2.nix
    ./services/gpg-agent.nix
    ./services/kubo.nix
    ./services/pueue.nix
  ];
}
