{
  imports = [
    ./misc/data.nix
    ./misc/home.nix
    ./misc/nix.nix
    ./misc/opengl.nix
    ./misc/xdg-desktop-entries.nix

    ./programs/bpython.nix
    ./programs/discord.nix
    ./programs/element.nix
    ./programs/ferdium.nix
    ./programs/fish.nix
    ./programs/glab.nix
    ./programs/glow.nix
    ./programs/hub.nix
    ./programs/kde.nix
    ./programs/kitty.nix
    ./programs/litecli.nix
    ./programs/mux.nix
    ./programs/neovim.nix
    ./programs/nix-init.nix
    ./programs/nvchecker.nix
    ./programs/paru.nix
    ./programs/pgcli.nix
    ./programs/powerline.nix
    ./programs/ptpython.nix
    ./programs/sccache.nix
    ./programs/silicon.nix
    ./programs/ssh.nix
    ./programs/starship.nix
    ./programs/taplo.nix
    ./programs/tmux.nix
    ./programs/xh.nix

    ./services/aria2.nix
    ./services/kubo.nix
    ./services/module-server.nix
    ./services/nix-web.nix
    ./services/sccache.nix
  ];
}
